title: Rafael Avilar - Portfólio Visualização Científica (2021.2)
description: Site para arquivar exercícios e trabalhos relevantes a disciplina de Visualização Científica.
theme: jekyll-theme-cayman
